In [2]:
import numpy as np
import pandas as pd

In [3]:
train = np.load('fashion_train.npy') 

In [12]:
train.shape[1]

785

In [14]:
y = train[:, -1]
X = train[:, :-1]

In [16]:
X.shape

(10000, 784)

In [17]:
np.unique(y)

array([0, 1, 2, 3, 4], dtype=uint8)

In [32]:
def gini_impurity(y):
    all_classes = np.unique(y)
    s = 0
    for i in all_classes:
        p = np.sum(y == i) / len(y)
        s += p**2
    return 1-s



In [47]:
matrix = train

temp_gini = 1000000
temp_i = 0
temp_j = 0

for j in range(matrix.shape[1]-1):
    
    for i in range(matrix.shape[0]-1):
        split1 = matrix[matrix[:, j] >= matrix[i, j]]
        gini1=gini_impurity(split1[:, -1])
        split2 = matrix[matrix[:, j] < matrix[i, j]]
        gini2=gini_impurity(split2[:, -1])
        weight1 = len(split1) / len(matrix)
        weight2 = len(split2) / len(matrix)
        gini = weight1 * gini1 + weight2 * gini2
        if gini < temp_gini:
            temp_gini = gini
            temp_i = i
            temp_j = j
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13


KeyboardInterrupt: 

In [51]:

print(temp_i, temp_j, temp_gini)


73 11 0.7665375667271068


In [45]:
matrix = train

matrix[matrix[:, 0] >= matrix[0, 0]]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=uint8)

In [42]:
matrix[: 1]

array([[  0,   0,   0,   0,   0,   3,   0,   0,   0,  41,  92, 172, 100,
         23,  22,  33, 104, 136,  93,  44,   0,   0,   0,   2,   0,   0,
          0,   0,   0,   0,   0,   0,   2,   0,   6, 119, 166, 177, 159,
        153, 227, 232, 215, 240, 227, 156, 162, 180, 175, 102,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   2,   0,  16, 166, 143, 133,
        126, 134, 121, 102, 146, 171, 160, 106, 113, 130, 130, 136, 151,
        159,   0,   0,   1,   0,   0,   0,   0,   0,   1,   0, 105, 139,
        123, 130, 129, 133, 133, 134, 116, 108, 113, 129, 135, 136, 131,
        128, 126, 150,  77,   0,   2,   0,   0,   0,   0,   0,   0,   2,
        151, 128, 126, 129, 130, 131, 130, 129, 131, 135, 134, 130, 130,
        131, 130, 130, 130, 139, 138,   0,   0,   0,   0,   0,   0,   0,
          0,  44, 148, 129, 126, 130, 133, 129, 129, 130, 130, 129, 129,
        130, 129, 131, 130, 131, 125, 146, 165,   2,   0,   0,   0,   0,
          0,   0,   0,  93, 156, 148, 124, 126, 126

In [22]:
j = 0
i = 0
test = X[:, j] > X[i, j]

In [25]:
matrix = train
colunm_index = 0
condition_value = 0


finted_row = matrix[matrix[: colunm_index] > condition_value]

In [ ]:
import numpy as np

def gini_impurity(counts, total):
    """
    Computes Gini impurity from class counts and total elements.
    """
    s = sum( (count / total)**2 for count in counts)
    return 1 - s

def best_split(matrix):
    temp_gini = float("inf")
    temp_i = None
    temp_j = None
    
    # Iterate over each feature
    for j in range(matrix.shape[1] - 1):
        # Sort rows by the feature column `j`
        sorted_matrix = matrix[matrix[:, j].argsort()]
        y_sorted = sorted_matrix[:, -1]
        
        # Track class counts for split
        left_class_counts = np.zeros(len(np.unique(y_sorted)))
        right_class_counts = np.bincount(y_sorted.astype(int))
        total = len(y_sorted)
        
        for i in range(1, total):
            cls = int(y_sorted[i - 1])
            left_class_counts[cls] += 1
            right_class_counts[cls] -= 1

            # Skip duplicate feature values to avoid redundant splits
            if sorted_matrix[i, j] == sorted_matrix[i - 1, j]:
                continue

            # Calculate Gini for left and right splits
            weight_left = i / total
            weight_right = 1 - weight_left
            gini_left = gini_impurity(left_class_counts, i)
            gini_right = gini_impurity(right_class_counts, total - i)
            gini = weight_left * gini_left + weight_right * gini_right

            # Update the best split if current Gini is lower
            if gini < temp_gini:
                temp_gini = gini
                temp_i = i
                temp_j = j

    return temp_gini, temp_i, temp_j

# Example usage
best_gini, best_i, best_j = best_split(train)
print("Best Gini:", best_gini)
print("Best split at row:", best_i, "column:", best_j)


Best Gini: 0.6532301649304489
Best split at row: 1782 column: 546
